import OAI.Analysis.TraceCone.Basic
import Mathlib.Analysis.CStarAlgebra.ApproximateUnit
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Range
import Mathlib.Tactic.NoncommRing

namespace OAI

/-!
# Finite ideals of extended traces

For an extended trace, the norm closure of the square-integrable ideal is the
closed ideal generated by the finite-trace positive elements. Positive elements
belong to this ideal exactly when each positive cut has finite trace.
This gives the scalar limit at zero in the canonical trace convergence of
*The trace cone classifies Razak–Jacelon stabilizations*, Section 2.
-/

noncomputable section

open Filter Topology Unitization CStarAlgebra
open scoped NNReal ENNReal

namespace TraceConeClassification

variable {A : Type*} [NonUnitalCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]

/-- Approximate-unit estimate in the original nonunital algebra. -/
lemma residual_norm_bound {x b e : A} (hb : 0 ≤ b)
    (hxb : star x * x ≤ b) (he : IsSelfAdjoint e) (he1 : ‖e‖ ≤ 1) :
    ‖x - x * e‖ ^ 2 ≤ 2 * ‖b - e * b‖ := by
  have heS : star e = e := he.star_eq
  have hr : 0 ≤ b - e * b - b * e + e * b * e := by
    rw [← inr_nonneg_iff (A := A)]
    have hn := star_left_conjugate_nonneg (Unitization.inr_nonneg_iff.mpr hb) (1 - (e : A⁺¹))
    convert hn using 1
    simp only [inr_add, inr_sub, inr_mul, star_sub, star_one, ← inr_star, heS]
    noncomm_ring
  have hle : star (x - x * e) * (x - x * e) ≤ b - e * b - b * e + e * b * e := by
    rw [← inr_le_inr_iff]
    have hh := star_left_conjugate_le_conjugate
      (inr_le_inr_iff.mpr hxb) (1 - (e : A⁺¹))
    convert hh using 1 <;>
      simp only [inr_add, inr_sub, inr_mul, star_sub, star_one, ← inr_star, star_mul, heS] <;>
      noncomm_ring
  calc
    ‖x - x * e‖ ^ 2 = ‖star (x - x * e) * (x - x * e)‖ := by
      rw [CStarRing.norm_star_mul_self, pow_two]
    _ ≤ ‖b - e * b - b * e + e * b * e‖ := CStarAlgebra.norm_le_norm_of_le_of_nonneg hle (star_mul_self_nonneg _)
    _ = ‖(b - e * b) - (b - e * b) * e‖ := by congr 1; noncomm_ring
    _ ≤ ‖b - e * b‖ + ‖(b - e * b) * e‖ := norm_sub_le _ _
    _ ≤ ‖b - e * b‖ + ‖b - e * b‖ * ‖e‖ := add_le_add_right (norm_mul_le _ _) _
    _ ≤ 2 * ‖b - e * b‖ := by nlinarith [norm_nonneg (b - e * b)]

/-- A closed absorbing star ideal contains elements whose square is dominated by one of its positives. -/
lemma closed_ideal_mem_of_square_le
    (I : NonUnitalStarSubalgebra ℂ A) (hI : IsClosed (I : Set A))
    (hleft : ∀ (x y : A), y ∈ I → x * y ∈ I)
    {x b : A} (hb : 0 ≤ b) (hxb : star x * x ≤ b) (hbI : b ∈ I) : x ∈ I := by
  let : IsClosed (I : Set A) := hI
  let : PartialOrder I := CStarAlgebra.spectralOrder I
  let : StarOrderedRing I := CStarAlgebra.spectralOrderedRing I
  let l := CStarAlgebra.approximateUnit I
  have hl : l.IsIncreasingApproximateUnit := CStarAlgebra.increasingApproximateUnit I
  have : l.NeBot := hl.toIsApproximateUnit.neBot
  have hbt : Tendsto (fun e : I => (e : A) * b) l (𝓝 b) := by
    have h := hl.tendsto_mul_right (⟨b, hbI⟩ : I)
    exact continuous_subtype_val.tendsto _ |>.comp h
  have hzero : Tendsto (fun e : I => 2 * ‖b - (e : A) * b‖) l (𝓝 0) := by
    simpa using (((tendsto_const_nhds (x := b)).sub hbt).norm.const_mul (2 : ℝ))
  have hsq : Tendsto (fun e : I => ‖x - x * (e : A)‖ ^ 2) l (𝓝 0) := by
    apply squeeze_zero' (Eventually.of_forall fun _ => sq_nonneg _) _ hzero
    filter_upwards [hl.eventually_isSelfAdjoint, hl.eventually_norm] with e he he1
    exact residual_norm_bound hb hxb (he.map (NonUnitalStarSubalgebraClass.subtype I)) he1
  have hn : Tendsto (fun e : I => ‖x - x * (e : A)‖) l (𝓝 0) := by
    have h := (Real.continuous_sqrt.tendsto 0).comp hsq
    simpa only [Function.comp_def, Real.sqrt_sq (norm_nonneg _), Real.sqrt_zero] using h
  have hxlim : Tendsto (fun e : I => x * (e : A)) l (𝓝 x) := by
    rw [tendsto_iff_norm_sub_tendsto_zero]
    simpa only [norm_sub_rev] using hn
  exact hI.mem_of_tendsto hxlim (Eventually.of_forall fun e => hleft x e e.2)

/-- A closed two-sided star ideal is hereditary. -/
theorem closed_ideal_hereditary
    (I : NonUnitalStarSubalgebra ℂ A) (hI : IsClosed (I : Set A))
    (hleft : ∀ (x y : A), y ∈ I → x * y ∈ I)
    (_hright : ∀ (x y : A), x ∈ I → x * y ∈ I)
    {a b : A} (ha : 0 ≤ a) (hab : a ≤ b) (hb : b ∈ I) : a ∈ I := by
  have hsq : star (CFC.sqrt a) * CFC.sqrt a = a := by
    rw [(CFC.sqrt_nonneg a).isSelfAdjoint.star_eq, CFC.sqrt_mul_sqrt_self _ ha]
  have hs : CFC.sqrt a ∈ I := closed_ideal_mem_of_square_le I hI hleft (ha.trans hab)
    (by rw [hsq]; exact hab) hb
  have hsS : star (CFC.sqrt a) ∈ I := star_mem hs
  have hm : star (CFC.sqrt a) * CFC.sqrt a ∈ I := I.mul_mem hsS hs
  rwa [hsq] at hm

lemma closed_ideal_star_mul_mem_iff
    (I : NonUnitalStarSubalgebra ℂ A) (hI : IsClosed (I : Set A))
    (hleft : ∀ (x y : A), y ∈ I → x * y ∈ I) (x : A) :
    star x * x ∈ I ↔ x ∈ I := by
  constructor
  · exact closed_ideal_mem_of_square_le I hI hleft (star_mul_self_nonneg x) le_rfl
  · exact hleft (star x) x

open Classical in
/-- The literal ideal weight `ι_I` of `st:ideals`, retaining all infinity values. -/
theorem closed_ideal_weight_exists
    (I : NonUnitalStarSubalgebra ℂ A) (hI : IsClosed (I : Set A))
    (hleft : ∀ (x y : A), y ∈ I → x * y ∈ I)
    (hright : ∀ (x y : A), x ∈ I → x * y ∈ I) :
    ∃ τ : ExtendedTrace A, ∀ a : Positive A, τ a = if a.1 ∈ I then 0 else ∞ := by
  classical
  let f : Positive A → ℝ≥0∞ := fun a => if a.1 ∈ I then 0 else ∞
  have hadd (a b : Positive A) : (a.1 + b.1 ∈ I) ↔ (a.1 ∈ I ∧ b.1 ∈ I) := by
    constructor
    · intro h
      exact ⟨closed_ideal_hereditary I hI hleft hright a.2 (le_add_of_nonneg_right b.2) h,
        closed_ideal_hereditary I hI hleft hright b.2 (le_add_of_nonneg_left a.2) h⟩
    · exact fun h => I.add_mem h.1 h.2
  have hscale (r : ℝ) (a : A) (ha : a ∈ I) : r • a ∈ I := by
    have h : (r : ℂ) • a ∈ I := I.smul_mem (r : ℂ) ha
    simpa only [Complex.coe_smul] using h
  have hscale_iff (r : ℝ≥0) (hr : 0 < r) (a : Positive A) :
      (Positive.scale r a).1 ∈ I ↔ a.1 ∈ I := by
    constructor
    · intro h
      have hm := hscale (r : ℝ)⁻¹ _ h
      simpa only [Positive.scale, inv_smul_smul₀ (show (r : ℝ) ≠ 0 by exact_mod_cast hr.ne')] using hm
    · exact hscale r a.1
  refine ⟨{
    toFun := f
    map_zero := by simp [f, Positive.zero]
    map_add := ?_
    map_scale := ?_
    tracial := ?_
    lowerSemicontinuous := ?_ }, fun _ => rfl⟩
  · intro a b
    dsimp [f, Positive.add]
    rw [hadd]
    by_cases ha : a.1 ∈ I <;> by_cases hb : b.1 ∈ I <;> simp [ha, hb]
  · intro r hr a
    dsimp [f]
    rw [hscale_iff r hr a]
    by_cases ha : a.1 ∈ I
    · simp [ha]
    · simp [ha, ENNReal.coe_ne_zero.mpr hr.ne']
  · intro x
    have hm : star x * x ∈ I ↔ x * star x ∈ I := by
      rw [closed_ideal_star_mul_mem_iff I hI hleft x]
      constructor
      · intro hx
        exact hleft x (star x) (star_mem hx)
      · intro hx
        have hs : star x ∈ I := (closed_ideal_star_mul_mem_iff I hI hleft (star x)).mp (by simpa using hx)
        simpa only [star_star] using star_mem hs
    simp only [f, Positive.starMul, Positive.mulStar, hm]
  · rw [lowerSemicontinuous_iff_isClosed_preimage]
    intro y
    by_cases hy : y = ∞
    · subst y
      simp
    · have heq : f ⁻¹' Set.Iic y = {a : Positive A | a.1 ∈ I} := by
        ext a
        by_cases ha : a.1 ∈ I <;> simp [f, ha, hy]
      rw [heq]
      exact hI.preimage continuous_subtype_val

namespace ExtendedTrace

variable (τ : ExtendedTrace A)

/-- The two-sided square-integrable ideal, before taking its norm closure. -/
def finiteSquareSet : Set A := {x | τ (Positive.starMul x) < ∞}

lemma zero_mem_finiteSquareSet : (0 : A) ∈ τ.finiteSquareSet := by
  simpa [finiteSquareSet, Positive.starMul, Positive.zero] using
    (τ.map_zero ▸ ENNReal.zero_lt_top : τ Positive.zero < ∞)

lemma star_mem_finiteSquareSet {x : A} (hx : x ∈ τ.finiteSquareSet) :
    star x ∈ τ.finiteSquareSet := by
  change τ (Positive.starMul (star x)) < ∞
  have heq : Positive.starMul (star x) = Positive.mulStar x := by
    apply Subtype.ext
    simp [Positive.starMul, Positive.mulStar]
  rw [heq, ← τ.tracial]
  exact hx

lemma smul_mem_finiteSquareSet (c : ℂ) {x : A} (hx : x ∈ τ.finiteSquareSet) :
    c • x ∈ τ.finiteSquareSet := by
  let r : ℝ≥0 := ⟨Complex.normSq c, Complex.normSq_nonneg c⟩
  have heq : Positive.starMul (c • x) = Positive.scale r (Positive.starMul x) := by
    apply Subtype.ext
    dsimp [Positive.starMul, Positive.scale, r]
    simp only [star_smul, smul_mul_assoc, mul_smul_comm, smul_smul]
    change (c * star c) • (star x * x) = (Complex.normSq c : ℝ) • (star x * x)
    rw [mul_comm c (star c)]
    change ((starRingEnd ℂ) c * c) • (star x * x) = _
    rw [← Complex.normSq_eq_conj_mul_self, Complex.coe_smul]
  change τ (Positive.starMul (c • x)) < ∞
  rw [heq, τ.map_scale_all]
  exact ENNReal.mul_lt_top ENNReal.coe_lt_top hx

lemma add_mem_finiteSquareSet {x y : A}
    (hx : x ∈ τ.finiteSquareSet) (hy : y ∈ τ.finiteSquareSet) :
    x + y ∈ τ.finiteSquareSet := by
  have hb : star (x + y) * (x + y) ≤ (2 : ℝ) • (star x * x + star y * y) := by
    apply sub_nonneg.mp
    convert star_mul_self_nonneg (x - y) using 1
    simp only [two_smul, star_add, star_sub, mul_add, add_mul, mul_sub, sub_mul]
    noncomm_ring
  calc
    τ (Positive.starMul (x + y)) ≤
        τ (Positive.scale 2 (Positive.add (Positive.starMul x) (Positive.starMul y))) :=
      τ.monotone hb
    _ < ∞ := by
      rw [τ.map_scale_all, τ.map_add]
      exact ENNReal.mul_lt_top ENNReal.coe_lt_top (ENNReal.add_lt_top.mpr ⟨hx, hy⟩)

lemma mul_mem_finiteSquareSet_left (x : A) {y : A} (hy : y ∈ τ.finiteSquareSet) :
    x * y ∈ τ.finiteSquareSet := by
  have hb : star (x * y) * (x * y) ≤ ‖star x * x‖ • (star y * y) := by
    simpa only [star_mul, mul_assoc] using
      (CStarAlgebra.star_left_conjugate_le_norm_smul (a := y) (b := star x * x))
  calc
    τ (Positive.starMul (x * y)) ≤
        τ (Positive.scale ‖star x * x‖₊ (Positive.starMul y)) := τ.monotone hb
    _ < ∞ := by
      rw [τ.map_scale_all]
      exact ENNReal.mul_lt_top ENNReal.coe_lt_top hy

lemma mul_mem_finiteSquareSet_right {x : A} (hx : x ∈ τ.finiteSquareSet) (y : A) :
    x * y ∈ τ.finiteSquareSet := by
  simpa only [star_mul, star_star] using
    τ.star_mem_finiteSquareSet (τ.mul_mem_finiteSquareSet_left (star y) (τ.star_mem_finiteSquareSet hx))

def finiteSquareAlgebra : NonUnitalStarSubalgebra ℂ A where
  carrier := τ.finiteSquareSet
  zero_mem' := τ.zero_mem_finiteSquareSet
  add_mem' := τ.add_mem_finiteSquareSet
  smul_mem' := τ.smul_mem_finiteSquareSet
  mul_mem' := fun _ hy => τ.mul_mem_finiteSquareSet_left _ hy
  star_mem' := τ.star_mem_finiteSquareSet

/-- The closed ideal generated by the finite-trace positive elements. -/
def finiteIdeal : NonUnitalStarSubalgebra ℂ A := τ.finiteSquareAlgebra.topologicalClosure

lemma isClosed_finiteIdeal : IsClosed (τ.finiteIdeal : Set A) :=
  NonUnitalStarSubalgebra.isClosed_topologicalClosure _

lemma mul_mem_finiteIdeal_left (x : A) {y : A} (hy : y ∈ τ.finiteIdeal) :
    x * y ∈ τ.finiteIdeal := by
  change y ∈ closure (τ.finiteSquareAlgebra : Set A) at hy
  change x * y ∈ closure (τ.finiteSquareAlgebra : Set A)
  exact (map_mem_closure (continuous_const.mul continuous_id) hy)
    (fun z hz => τ.mul_mem_finiteSquareSet_left x hz)

lemma mul_mem_finiteIdeal_right {x : A} (hx : x ∈ τ.finiteIdeal) (y : A) :
    x * y ∈ τ.finiteIdeal := by
  simpa only [star_mul, star_star] using
    star_mem (τ.mul_mem_finiteIdeal_left (star y) (star_mem hx))

lemma positive_mem_finiteIdeal_of_finite (a : Positive A) (ha : τ a < ∞) :
    a.1 ∈ τ.finiteIdeal := by
  have hs : CFC.sqrt a.1 ∈ τ.finiteSquareAlgebra := by
    have heq : Positive.starMul (CFC.sqrt a.1) = a := by
      apply Subtype.ext
      dsimp [Positive.starMul]
      rw [(CFC.sqrt_nonneg a.1).isSelfAdjoint.star_eq, CFC.sqrt_mul_sqrt_self _ a.2]
    change τ (Positive.starMul (CFC.sqrt a.1)) < ∞
    rwa [heq]
  have hm : CFC.sqrt a.1 * CFC.sqrt a.1 ∈ τ.finiteSquareAlgebra :=
    τ.finiteSquareAlgebra.mul_mem hs hs
  rw [CFC.sqrt_mul_sqrt_self _ a.2] at hm
  exact NonUnitalStarSubalgebra.le_topologicalClosure _ hm

lemma finiteIdeal_le_iff (J : NonUnitalStarSubalgebra ℂ A)
    (hJ : IsClosed (J : Set A))
    (hleft : ∀ (x y : A), y ∈ J → x * y ∈ J)
    (_hright : ∀ (x y : A), x ∈ J → x * y ∈ J) :
    τ.finiteIdeal ≤ J ↔ ∀ a : Positive A, τ a < ∞ → a.1 ∈ J := by
  constructor
  · intro h a ha
    exact h (τ.positive_mem_finiteIdeal_of_finite a ha)
  · intro h
    apply NonUnitalStarSubalgebra.topologicalClosure_minimal _ (ht := hJ)
    intro x hx
    exact closed_ideal_mem_of_square_le J hJ hleft (star_mul_self_nonneg x) le_rfl
      (h (Positive.starMul x) hx)


lemma finite_positive_dense (a : Positive A) (ha : a.1 ∈ τ.finiteIdeal) :
    ∃ b : ℕ → Positive A, (∀ n, τ (b n) < ∞) ∧ Tendsto b atTop (𝓝 a) := by
  let : IsClosed (τ.finiteIdeal : Set A) := τ.isClosed_finiteIdeal
  have hs : CFC.sqrt a.1 ∈ τ.finiteIdeal := by
    rw [CFC.sqrt_eq_real_sqrt _ a.2]
    exact cfcₙ_mem (𝕜' := ℂ) Real.sqrt ha
  change CFC.sqrt a.1 ∈ closure (τ.finiteSquareAlgebra : Set A) at hs
  obtain ⟨x, hx, hlim⟩ := mem_closure_iff_seq_limit.mp hs
  refine ⟨fun n => Positive.starMul (x n), hx, ?_⟩
  have hc : Continuous (fun x : A => Positive.starMul x) := by
    unfold Positive.starMul
    fun_prop
  have heq : Positive.starMul (CFC.sqrt a.1) = a := by
    apply Subtype.ext
    dsimp [Positive.starMul]
    rw [(CFC.sqrt_nonneg a.1).isSelfAdjoint.star_eq, CFC.sqrt_mul_sqrt_self _ a.2]
  simpa only [heq, Function.comp_def] using (hc.tendsto _).comp hlim

lemma positive_mem_finiteIdeal_iff_cuts (a : Positive A) :
    a.1 ∈ τ.finiteIdeal ↔ ∀ (ε : ℝ≥0), 0 < ε → τ (Positive.cut a ε) < ∞ := by
  constructor
  · intro ha ε hε
    obtain ⟨b, hb, ht⟩ := τ.finite_positive_dense a ha
    have ht' : Tendsto (fun n => (b n).1) atTop (𝓝 a.1) := tendsto_subtype_rng.mp ht
    have hnear : ∀ᶠ n in atTop, ‖a.1 - (b n).1‖ < ε := by
      have hnorm : Tendsto (fun n => ‖a.1 - (b n).1‖) atTop (𝓝 0) := by
        simpa using ((tendsto_const_nhds (x := a.1)).sub ht').norm
      exact hnorm.eventually (gt_mem_nhds (show (0 : ℝ) < ε from hε))
    obtain ⟨n, hn⟩ := hnear.exists
    exact trace_cut_finite_of_near_finite τ a (b n) ε hε hn (hb n)
  · intro h
    apply τ.isClosed_finiteIdeal.mem_of_tendsto
      ((continuous_subtype_val.tendsto a).comp (Positive.tendsto_cut_reciprocal a))
    exact Eventually.of_forall fun n =>
      τ.positive_mem_finiteIdeal_of_finite _ (h (1 / (n + 1)) (by positivity))

end ExtendedTrace


/-- Positive scalar multiples of a finite trace value tend to zero. -/
lemma tendsto_scale_zero_of_finite (τ : ExtendedTrace A) (a : Positive A)
    (ha : τ a < ∞) :
    Tendsto (fun r : ℝ≥0 => τ.scale r a) (𝓝[>] 0) (𝓝 0) := by
  have ht := ((ENNReal.continuous_mul_const ha.ne).comp ENNReal.continuous_coe).tendsto
    (0 : ℝ≥0)
  simpa only [ExtendedTrace.scale_apply, Function.comp_def, ENNReal.coe_zero, zero_mul] using
    ht.mono_left nhdsWithin_le_nhds

open Classical in
/-- Exact finite-domain ideal and its scalar-limit weight. Its universal property
is the manuscript's closed ideal generated by the finite-trace positives. -/
theorem finite_domain_ideal_and_scalar_limit (τ : ExtendedTrace A) :
    ∃ I : NonUnitalStarSubalgebra ℂ A,
      IsClosed (I : Set A) ∧
      (∀ (x y : A), y ∈ I → x * y ∈ I) ∧
      (∀ (x y : A), x ∈ I → x * y ∈ I) ∧
      (∀ J : NonUnitalStarSubalgebra ℂ A, IsClosed (J : Set A) →
        (∀ (x y : A), y ∈ J → x * y ∈ J) →
        (∀ (x y : A), x ∈ J → x * y ∈ J) →
        (I ≤ J ↔ ∀ a : Positive A, τ a < ∞ → a.1 ∈ J)) ∧
      (∀ a : Positive A, a.1 ∈ I ↔
        ∀ (ε : ℝ≥0), 0 < ε → τ (Positive.cut a ε) < ∞) ∧
      ∃ ω : ExtendedTrace A,
        (∀ a : Positive A, ω a = if a.1 ∈ I then 0 else ∞) ∧
        CanonicalConvergence A (𝓝[>] (0 : ℝ≥0)) (fun r => τ.scale r) ω := by
  let I := τ.finiteIdeal
  have hl : ∀ (x y : A), y ∈ I → x * y ∈ I :=
    fun x _ hy => τ.mul_mem_finiteIdeal_left x hy
  have hr : ∀ (x y : A), x ∈ I → x * y ∈ I :=
    fun _ y hx => τ.mul_mem_finiteIdeal_right hx y
  obtain ⟨ω, hω⟩ := closed_ideal_weight_exists I τ.isClosed_finiteIdeal hl hr
  refine ⟨I, τ.isClosed_finiteIdeal, hl, hr, τ.finiteIdeal_le_iff,
    τ.positive_mem_finiteIdeal_iff_cuts, ω, hω, ?_⟩
  intro a ε hε
  rw [hω a]
  by_cases ha : a.1 ∈ I
  · simp only [ha, ite_true]
    constructor
    · have hc := (τ.positive_mem_finiteIdeal_iff_cuts a).mp ha ε hε
      exact le_of_eq (tendsto_scale_zero_of_finite τ _ hc).limsup_eq
    · exact bot_le
  · simp only [ha, ite_false]
    refine ⟨le_top, ?_⟩
    have ht : τ a = ∞ := by
      by_contra ht
      exact ha (τ.positive_mem_finiteIdeal_of_finite a (lt_top_iff_ne_top.mpr ht))
    have he : (fun r : ℝ≥0 => τ.scale r a) =ᶠ[𝓝[>] 0] (fun _ => ∞) := by
      filter_upwards [self_mem_nhdsWithin] with r hr
      rw [ExtendedTrace.scale_apply, ht]
      exact ENNReal.mul_top (ENNReal.coe_ne_zero.mpr (ne_of_gt hr))
    have hlim : Tendsto (fun r : ℝ≥0 => τ.scale r a) (𝓝[>] 0) (𝓝 ∞) :=
      tendsto_const_nhds.congr' he.symm
    exact le_of_eq hlim.liminf_eq.symm

end TraceConeClassification

end

end OAI
